//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitMsgs
{
    [Serializable]
    public class PickupFeedback : Message
    {
        public const string k_RosMessageName = "moveit_msgs-3175099a2b7fa75f74c36850a716b0fe603c8947/Pickup";
        public override string RosMessageName => k_RosMessageName;

        //  The internal state that the pickup action currently is in
        public string state;

        public PickupFeedback()
        {
            this.state = "";
        }

        public PickupFeedback(string state)
        {
            this.state = state;
        }

        public static PickupFeedback Deserialize(MessageDeserializer deserializer) => new PickupFeedback(deserializer);

        private PickupFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "PickupFeedback: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
