//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class FollowJointTrajectoryFeedback : Message
    {
        public const string k_RosMessageName = "control_msgs/FollowJointTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public string[] joint_names;
        public Trajectory.JointTrajectoryPointMsg desired;
        public Trajectory.JointTrajectoryPointMsg actual;
        public Trajectory.JointTrajectoryPointMsg error;

        public FollowJointTrajectoryFeedback()
        {
            this.header = new HeaderMsg();
            this.joint_names = new string[0];
            this.desired = new Trajectory.JointTrajectoryPointMsg();
            this.actual = new Trajectory.JointTrajectoryPointMsg();
            this.error = new Trajectory.JointTrajectoryPointMsg();
        }

        public FollowJointTrajectoryFeedback(HeaderMsg header, string[] joint_names, Trajectory.JointTrajectoryPointMsg desired, Trajectory.JointTrajectoryPointMsg actual, Trajectory.JointTrajectoryPointMsg error)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.desired = desired;
            this.actual = actual;
            this.error = error;
        }

        public static FollowJointTrajectoryFeedback Deserialize(MessageDeserializer deserializer) => new FollowJointTrajectoryFeedback(deserializer);

        private FollowJointTrajectoryFeedback(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            this.desired = Trajectory.JointTrajectoryPointMsg.Deserialize(deserializer);
            this.actual = Trajectory.JointTrajectoryPointMsg.Deserialize(deserializer);
            this.error = Trajectory.JointTrajectoryPointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.Write(this.desired);
            serializer.Write(this.actual);
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "FollowJointTrajectoryFeedback: " +
            "\nheader: " + header.ToString() +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\ndesired: " + desired.ToString() +
            "\nactual: " + actual.ToString() +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
