//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchUnity
{
    [Serializable]
    public class PoseQueryServiceRequest : Message
    {
        public const string k_RosMessageName = "fetch_unity/PoseQueryService";
        public override string RosMessageName => k_RosMessageName;

        public FetchMoveitJointsTorsoMsg start_joints_torso;
        public FetchMoveitJointsMsg start_joints;
        public Geometry.PoseMsg end_pose;

        public PoseQueryServiceRequest()
        {
            this.start_joints_torso = new FetchMoveitJointsTorsoMsg();
            this.start_joints = new FetchMoveitJointsMsg();
            this.end_pose = new Geometry.PoseMsg();
        }

        public PoseQueryServiceRequest(FetchMoveitJointsTorsoMsg start_joints_torso, FetchMoveitJointsMsg start_joints, Geometry.PoseMsg end_pose)
        {
            this.start_joints_torso = start_joints_torso;
            this.start_joints = start_joints;
            this.end_pose = end_pose;
        }

        public static PoseQueryServiceRequest Deserialize(MessageDeserializer deserializer) => new PoseQueryServiceRequest(deserializer);

        private PoseQueryServiceRequest(MessageDeserializer deserializer)
        {
            this.start_joints_torso = FetchMoveitJointsTorsoMsg.Deserialize(deserializer);
            this.start_joints = FetchMoveitJointsMsg.Deserialize(deserializer);
            this.end_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start_joints_torso);
            serializer.Write(this.start_joints);
            serializer.Write(this.end_pose);
        }

        public override string ToString()
        {
            return "PoseQueryServiceRequest: " +
            "\nstart_joints_torso: " + start_joints_torso.ToString() +
            "\nstart_joints: " + start_joints.ToString() +
            "\nend_pose: " + end_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
