//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RelaxedIkRos1
{
    [Serializable]
    public class EEPoseGoalsMsg : Message
    {
        public const string k_RosMessageName = "relaxed_ik_ros1/EEPoseGoals";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.PoseMsg[] ee_poses;

        public EEPoseGoalsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.ee_poses = new Geometry.PoseMsg[0];
        }

        public EEPoseGoalsMsg(Std.HeaderMsg header, Geometry.PoseMsg[] ee_poses)
        {
            this.header = header;
            this.ee_poses = ee_poses;
        }

        public static EEPoseGoalsMsg Deserialize(MessageDeserializer deserializer) => new EEPoseGoalsMsg(deserializer);

        private EEPoseGoalsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.ee_poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.ee_poses);
            serializer.Write(this.ee_poses);
        }

        public override string ToString()
        {
            return "EEPoseGoalsMsg: " +
            "\nheader: " + header.ToString() +
            "\nee_poses: " + System.String.Join(", ", ee_poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
