//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LfdReceiver
{
    [Serializable]
    public class RecordResponse : Message
    {
        public const string k_RosMessageName = "lfd_receiver/Record";
        public override string RosMessageName => k_RosMessageName;

        public Std.BoolMsg received;

        public RecordResponse()
        {
            this.received = new Std.BoolMsg();
        }

        public RecordResponse(Std.BoolMsg received)
        {
            this.received = received;
        }

        public static RecordResponse Deserialize(MessageDeserializer deserializer) => new RecordResponse(deserializer);

        private RecordResponse(MessageDeserializer deserializer)
        {
            this.received = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.received);
        }

        public override string ToString()
        {
            return "RecordResponse: " +
            "\nreceived: " + received.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
