//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DemonstrationReceiver
{
    [Serializable]
    public class RecordRequest : Message
    {
        public const string k_RosMessageName = "demonstration_receiver/Record";
        public override string RosMessageName => k_RosMessageName;

        public Std.BoolMsg begin;

        public RecordRequest()
        {
            this.begin = new Std.BoolMsg();
        }

        public RecordRequest(Std.BoolMsg begin)
        {
            this.begin = begin;
        }

        public static RecordRequest Deserialize(MessageDeserializer deserializer) => new RecordRequest(deserializer);

        private RecordRequest(MessageDeserializer deserializer)
        {
            this.begin = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.begin);
        }

        public override string ToString()
        {
            return "RecordRequest: " +
            "\nbegin: " + begin.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
